# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1394614509);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20131206041033");
user_pref("browser.startup.homepage_override.mstone", "24.2.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":3}");
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"firebug@software.joehewitt.com\":{\"version\":\"1.12.7\",\"type\":\"extension\",\"descriptor\":\"/root/Beaker-Auto/firefox/autouser2/extensions/firebug@software.joehewitt.com.xpi\"}}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "firefinder%40robertnyman.com:1.4,autoauth%40efinke.com:2.1,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:24.2.0");
user_pref("extensions.firebug.currentVersion", "1.12.7");
user_pref("extensions.firebug.toolbarCustomizationDone", true);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1386903430000,\"rdfTime\":1386321942000}}},{\"name\":\"app-profile\",\"addons\":{\"firefinder@robertnyman.com\":{\"descriptor\":\"/root/Beaker-Auto/firefox/autouser2/extensions/firefinder@robertnyman.com.xpi\",\"mtime\":1394614554000},\"autoauth@efinke.com\":{\"descriptor\":\"/root/Beaker-Auto/firefox/autouser2/extensions/autoauth@efinke.com.xpi\",\"mtime\":1394614554000},\"firebug@software.joehewitt.com\":{\"descriptor\":\"/root/Beaker-Auto/firefox/autouser2/extensions/firebug@software.joehewitt.com.xpi\",\"mtime\":1394614547000}}}]");
user_pref("extensions.lastAppVersion", "24.2.0");
user_pref("extensions.lastPlatformVersion", "24.2.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", true);
user_pref("gecko.buildID", "20131206041033");
user_pref("gecko.mstone", "24.2.0");
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1394615000);
user_pref("toolkit.telemetry.previousBuildID", "20131206041033");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1397206511);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
